POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjE3NTY5MTgsInVzZXJJZCI6MX0.0sw_iBakEXnpqtxY4K-tzwt4-W8jzAZjjPkCLSFVnsU

{
    "name": "Test Event 99",
    "description": "A test event",
    "location": "test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}