POST http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYxNzU3MDIyLCJ1c2VySWQiOjJ9.u51bpK7elWNA0mL-lIOi4IYlMM_NtdyoQJbfecOqBp0