PUT  http://localhost:8080/events/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjE3MzI2NzcsInVzZXJJZCI6MX0.kEDJ59ba76u0lSZBple6nKfgmHH_Qgz8Fsf8lGE3y7g

{
    "name": "Test Event updated",
    "description": "A test event",
    "location": "test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}
